name = "Poggy pack"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "851019465ba01de469b627ab1b2dda47efdee2a14c685cf6da9b4b73ce8c0153"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18-rc3", "1.18-rc4"]
