name = "Packy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ac4a95f5bba2f3772bc3296c3737313e0a65abd95d9285ebfebc09458a2cc27"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18-rc3", "1.18-rc4"]
