name = "Adorn"
filename = "Adorn-3.3.1+1.18.1-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/E6FUtRJh/versions/3.3.1-fabric/Adorn-3.3.1%2B1.18.1-fabric.jar"
hash-format = "sha1"
hash = "3fed1f7f0f547eb5380e67c959285ffdb61165cd"

[update]
[update.modrinth]
mod-id = "E6FUtRJh"
version = "VyILUVlk"
