name = "AppleSkin"
filename = "appleskin-fabric-mc1.18.1-2.3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/fabric-mc1.18.1-2.3.0/appleskin-fabric-mc1.18.1-2.3.0.jar"
hash-format = "sha1"
hash = "6ea8db565249f4b0c1322f291f09d345ffcc8dc7"

[update]
[update.modrinth]
mod-id = "EsAfCjCV"
version = "1l8O9vUa"
