name = "Custom Entity Models"
filename = "cem-0.7.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YOQCucah/versions/0.7.0/cem-0.7.0.jar"
hash-format = "sha1"
hash = "91c1a2ad7743118cc44d56a92f358ae09f4f8ba1"

[update]
[update.modrinth]
mod-id = "YOQCucah"
version = "Z42auxMF"
