name = "CIT Resewn"
filename = "CITResewn-0.9.1+1.18.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/otVJckYQ/versions/0.9.1+1.18.1/CITResewn-0.9.1+1.18.1.jar"
hash-format = "sha1"
hash = "a320fbe1f0f6c1364c6afb224f993ba4252e6206"

[update]
[update.modrinth]
mod-id = "otVJckYQ"
version = "PnxfNudU"
