name = "CompleteConfig"
filename = "completeconfig-lib-1.4.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GtqG8z1h/versions/1.4.0/completeconfig-lib-1.4.0.jar"
hash-format = "sha1"
hash = "b5a366584aa4c7bba8306b4f7233329fcbf609f1"

[update]
[update.modrinth]
mod-id = "GtqG8z1h"
version = "G45g4NU5"
