name = "Dank Storage Fabric"
filename = "dankstorage-1.18.1-3.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/483/dankstorage-1.18.1-3.5.4.jar"
hash-format = "sha1"
hash = "84b77884b41d4c797eab491b81adbcf38d4ca784"

[update]
[update.curseforge]
file-id = 3666483
project-id = 400619
