name = "Effective 💦"
filename = "effective-1.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3735/265/effective-1.2.jar"
hash-format = "sha1"
hash = "cbff7c32310dc47daefccb2e866ec641f7a96d90"

[update]
[update.curseforge]
file-id = 3735265
project-id = 556381
