name = "Enhanced Quarries (Fabric)"
filename = "EnhancedQuarries-1.18.2-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3724/30/EnhancedQuarries-1.18.2-1.2.1.jar"
hash-format = "sha1"
hash = "6b7452e3ad74819e14f7b016456739e3e4c0583a"

[update]
[update.curseforge]
file-id = 3724030
project-id = 528338
