name = "Extra Generators"
filename = "extra-generators-1.1.2-BETA+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3712/531/extra-generators-1.1.2-BETA+1.18.jar"
hash-format = "sha1"
hash = "2b5e755830860f992890847414c997eec5a6698d"

[update]
[update.curseforge]
file-id = 3712531
project-id = 475623
