name = "Fabricated Chisel"
filename = "chisel-1.4.3+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/4KWv7wbN/versions/1.4.3/chisel-1.4.3+1.18.1.jar"
hash-format = "sha1"
hash = "39ae361c091e8bfc43cadcdc86af4c703efe4ddb"

[update]
[update.modrinth]
mod-id = "4KWv7wbN"
version = "uqqGWxEb"
