name = "Flesh 2 Leather [FABRIC]"
filename = "1.18-flesh2leather-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/519/1.18-flesh2leather-1.0.2.jar"
hash-format = "sha1"
hash = "92dc5d7879a05eb6986b6ce5e791aee092e5e577"

[update]
[update.curseforge]
file-id = 3546519
project-id = 320932
