name = "Industrial Revolution"
filename = "indrev-1.13.8-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/959/indrev-1.13.8-BETA.jar"
hash-format = "sha1"
hash = "e3b51fd6a7cf7967d28c98b76ad0b7eb70159216"

[update]
[update.curseforge]
file-id = 3725959
project-id = 391708
