name = "Inventorio (Fabric)"
filename = "inventorio-1.18-fabric-1.6.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3553/574/inventorio-1.18-fabric-1.6.2.jar"
hash-format = "sha1"
hash = "304a3c03842a8b45e0f118e53cabf9500ae87bdd"

[update]
[update.curseforge]
file-id = 3553574
project-id = 491073
