name = "Leaf Decay"
filename = "leaf-decay-1.4.0-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/409/leaf-decay-1.4.0-1.18.1.jar"
hash-format = "sha1"
hash = "2235cf03c7ee91e033699260b631726f05254a42"

[update]
[update.curseforge]
file-id = 3646409
project-id = 320528
