name = "Lib Block Attributes"
filename = "libblockattributes-all-0.10.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3540/966/libblockattributes-all-0.10.0.jar"
hash-format = "sha1"
hash = "02f4ebf06942776cdcb19eb1459dce53aa6acae9"

[update]
[update.curseforge]
file-id = 3540966
project-id = 317995
