name = "Lifts"
filename = "lifts-1.4-BETA+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/LMEONxlN/versions/1.4-BETA+1.18/lifts-1.4-BETA+1.18.jar"
hash-format = "sha1"
hash = "f68678740c74657b9c8b890b04fc61f8d26f3dae"

[update]
[update.modrinth]
mod-id = "LMEONxlN"
version = "5uvJPclM"
