name = "Mo Glass"
filename = "Mo-Glass-1.6.1-MC1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3569/199/Mo-Glass-1.6.1-MC1.18.1.jar"
hash-format = "sha1"
hash = "46c314430a6167549f8ca1478430c21af797b6ca"

[update]
[update.curseforge]
file-id = 3569199
project-id = 353426
