name = "Mouse Wheelie"
filename = "mousewheelie-1.8.3+mc1.18-pre5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/u5Ic2U1u/versions/1.8.3+mc1.18-pre5/mousewheelie-1.8.3%2Bmc1.18-pre5.jar"
hash-format = "sha1"
hash = "b64f90a7392aa45ffd5272bcae98a3f6ba3a8d63"

[update]
[update.modrinth]
mod-id = "u5Ic2U1u"
version = "ymIYCJPX"
