name = "Mouse Wheelie"
filename = "mousewheelie-1.8.8+mc1.18-pre5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/u5Ic2U1u/versions/1.8.8+mc1.18-pre5/mousewheelie-1.8.8%2Bmc1.18-pre5.jar"
hash-format = "sha1"
hash = "b9c7403be3e1d5d534724f7b040de7718bc1e9f7"

[update]
[update.modrinth]
mod-id = "u5Ic2U1u"
version = "bCGRhsZx"
