name = "Presence Footsteps"
filename = "PresenceFootsteps-1.4.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/rcTfTZr3/versions/1.4.0/PresenceFootsteps-1.4.0.jar"
hash-format = "sha1"
hash = "9de4458abefaaebfdeadde8b1216f9a939a9fc87"

[update]
[update.modrinth]
mod-id = "rcTfTZr3"
version = "20NGWQNM"
