name = "Quarry Reborn"
filename = "quarry-reborn-1.18-0.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/792/quarry-reborn-1.18-0.5.5.jar"
hash-format = "sha1"
hash = "c02b83f06460d3de964c84a5bb26d26b2ebf345b"

[update]
[update.curseforge]
file-id = 3631792
project-id = 511254
