name = "spark"
filename = "spark-1.8.6-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.8.6-fabric/spark-1.8.6-fabric.jar"
hash-format = "sha1"
hash = "dc8c5f79d3129a0c28bb1b1c609c05e257149d2d"

[update]
[update.modrinth]
mod-id = "l6YH9Als"
version = "b3zKGLTS"
