name = "Trinkets"
filename = "trinkets-3.2.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/5aaWibi9/versions/3.2.0/trinkets-3.2.0.jar"
hash-format = "sha1"
hash = "4a31e5b5a00f44907d5f8f59c2c1b2501d92bb8e"

[update]
[update.modrinth]
mod-id = "5aaWibi9"
version = "DtvgyMK2"
