name = "UPC"
filename = "upc-0.0.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/zDLZFPAs/versions/0.0.1/upc-0.0.1.jar"
hash-format = "sha1"
hash = "fa08d31b51ba3e3a690385d49b11102982cdb541"

[update]
[update.modrinth]
mod-id = "zDLZFPAs"
version = "eruK26vY"
